hello world e API Flask
Marcos-Estevao/EP-targetdata pull request #3
Opened 2023-04-30 15:09 UTC by Marcos-Estevao

Adicionando Flask ao projeto. 
 Criei 1 API com Flask.
 Criei 3 endpoints com Flask.

No PyCharm vai no app.py e executa o método main, logo em seguida ira abrir um URL, basta clicar nele, para navegar basta digitar o comando http://127.0.0.1:5000/consultarEndereco, e ira abrir pra você consultar o endereço,  com esse URL http://127.0.0.1:5000 vai abrir Bem vindo ao meu site e o URL http://127.0.0.1:5000/contato ira aparecer Entre em contato conosco.

2023-04-30 15:22 UTC, marco-altran requested changes
O seu projeto não tem a dependência do Flask para executar o projeto.

Por favor crie um arquivo `requirements.txt` e adicione `Flask~=2.3.1` para incluir o Flask na lista de dependências do projeto.

2023-04-30 15:33 UTC, marco-altran commented
Sobre o que é o requirements.txt: https://jtemporal.com/requirements-txt/

2023-05-09 11:52 UTC, Marcos-Estevao commented
Criei um arquivo requirements.txt e adicionei a biblioteca Flask.

2023-05-10 14:11 UTC, marco-altran commented
@Marcos-Estevao eu não estou vendo nenhuma mudança no código. Tem certeza que vc fez o commit/push?

2023-05-10 16:55 UTC, marco-altran commented
O commit que vc mandou só tem algumas linhas em branco https://github.com/Marcos-Estevao/EP-targetdata/pull/3/commits/f2b45cc391b588dec6e3bf608eb9cace5f57af2d

2023-05-10 18:36 UTC, marco-altran reviewed
Boa! Tá quase bom, só precisa remover algumas linhas em branco que eu sinalizei.

2023-05-10 18:36 UTC, marco-altran commented on app.py
> +
Aqui deve ter somente duas linhas em branco

2023-05-10 18:36 UTC, marco-altran commented on app.py
> +
Aqui deve ter somente duas linhas em branco

2023-05-10 20:22 UTC, marco-altran approved these changes
Boa, pode fazer o merge 🚀 

Tome cuidado nas próximas vezes com as mensagens dos commits. Vc commitou tudo como "hello world e API Flask". A mensagem deve conter uma breve explicação do que vc está alterando.

2023-05-11 20:13 UTC, merged